# Generated by Django 5.2.7 on 2025-11-03 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, default='', max_length=32)),
                ('device_type', models.CharField(choices=[('light.yeelight', 'Yeelight Light'), ('doorbell.ring', 'Ring Doorbell'), ('unknown', 'Unknown')], default='unknown', max_length=64)),
                ('capabilities', models.JSONField(default=list)),
                ('vendor', models.CharField(blank=True, default='', max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_online', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
